### ISSUE TITLE
rust and rr

### ISSUE THREAD

**Issue by bitshifter** [RustSydney/talks#10]
I saw a blog post by Huon a while back about using the reverse debugger rr with Rust. It more about rr than Rust, but rr sounded like an interesting tool that it would be nice to get a bit of an intro and demo or something. On the other hand it seems unfair to make Huon prepare a talk for every meetup :) Perhaps someone else could volunteer. If I actually get around to trying it, I'll volunteer!

**Comment by caspark** [comment]
Oh, I missed [that blog post on rr](http://huonw.github.io/blog/2015/10/rreverse-debugging/) - having read it now, it would make a good topic for a talk! I'd only seen prototypes of such tools in my jvm travels.

cc @huonw though really anyone can probably dive in and talk about it.

**Comment by huonw** [comment]
It'd be great to have a talk about this! I'm happy to do it, but I think it'd be even more awesome if someone else did.

**Comment by bitshifter** [comment]
I can volunteer if you like. I will try put something quick together this weekend based on Huon's blog post.

**Comment by caspark** [comment]
No rush actually - we're in a great position with 3 talks for Meetup.7 - but of course it'd be great to line this one up for Meetup.8! (which'd be either mid Jan or mid-late Feb as I'll be away between those times)

**Comment by bitshifter** [comment]
Ah OK, cool, pressure off :)

**Comment by caspark** [comment]
@bitshifter would you like to have a shot at this talk for Meetup.8 on Tuesday February 16th?

**Comment by bitshifter** [comment]
I still haven't played with rr yet but could definitely throw something together by mid feb.

**Comment by caspark** [comment]
Excellent, I'll slot you in then.

**Comment by bitshifter** [comment]
Done! Slides are at https://bitshifter.github.io/rr+rust/

**Comment by caspark** [comment]
Recording: https://www.youtube.com/watch?v=ves_y06MCww

**Comment by yoshuawuyts** [comment]
that talk is so good!

**Comment by bitshifter** [comment]
Thanks!

Also, thanks for making the video Caspar.
