### ISSUE TITLE
My first 24 hours of game dev in Rust

### ISSUE THREAD

**Issue by MichaelShaw** [RustSydney/talks#17]
An intro game dev talk covering my approach to game dev in Rust, using Glium, and how I build an event driven game engine (in progress), and how that can be a good thing.

Will cover Glium, the virtues of value types, pattern matching and pure functions.

**Comment by caspark** [comment]
Let's book this one in for Sep 6.

**Comment by caspark** [comment]
Slides & code available at http://michaelshaw.io/
