### ISSUE TITLE
Hacking democracy with Rust

### ISSUE THREAD

**Issue by michaelsproul** [RustSydney/talks#18]
I've been implementing senate voting algorithms in Rust and would love a chance to talk about why I chose Rust for the project, and my experience using it.

https://github.com/michaelsproul/aus_senate

**Comment by caspark** [comment]
Sounds interesting! I'll get back to you with a date for meetup 10 :)

**Comment by michaelsproul** [comment]
Cool :)

**Comment by caspark** [comment]
Hey @michaelsproul , are you still up for giving a talk on this, say at a mid-late February Rust meetup, despite you raising this almost half a year ago?

**Comment by michaelsproul** [comment]
Yep! More than happy to! It actually works perfectly 'cause I have slides ready from my SF Rust talk :)

**Comment by caspark** [comment]
Great, I'll (edit: try to remember to) take a look on Monday what dates we have available for the next meetup.

**Comment by caspark** [comment]
Life intervened, but now that I have a few spare moments I can see that basically all the Mondays in Feb are free but no other Feb nights are. I've tentatively booked Feb 27th - does that work for you?

**Comment by michaelsproul** [comment]
Feb 27th should be fine, I'll mark it in my calendar!

**Comment by caspark** [comment]
Cool, I've scheduled the Atlassian side and announced via Meetup - see you then!
