### ISSUE TITLE
The ugly (and not-so-ugly) guts of Rust

### ISSUE THREAD

**Issue by jdub** [RustSydney/talks#2]
Want something on how Rust makes ugly and scary things all pretty and safe? I've been poking around at the guts of the Rust standard library, and could do a tour of things I've noticed and learned. There are a few lightbulb moments hidden away in there which might be interesting.

**Comment by caspark** [comment]
Hey, sorry for the slow reply - I stupidly forgot to watch the repository, so I didn't get the email notification.

That sounds like an interesting talk; will you be able to give it at this coming meetup (August 18th)?

**Comment by caspark** [comment]
Cool!

Anywhere from 5 to 30 minutes is fine; I try to aim for 20 minutes myself.

**Comment by jdub** [comment]
On Wed, Aug 5, 2015 at 5:31 PM, Caspar Krieger notifications@github.com
wrote:

> Anywhere from 5 to 30 minutes is fine; I try to aim for 20 minutes myself.

Cool, 20 minutes sounds great. See you there!

**Comment by caspark** [comment]
Thanks again for the talk. Would you please slap a link to your slides here as a comment (and optionally [on the meetup page](http://www.meetup.com/Rust-Sydney/events/223908978/))?

**Comment by caspark** [comment]
> Would you please slap a link to your slides here as a comment (and optionally on the meetup page)?

Nudge :)
