### ISSUE TITLE
An introduction to LLVM

### ISSUE THREAD

**Issue by tari** [RustSydney/talks#23]
As the author of [llvm-sys](https://crates.io/crates/llvm-sys), I'm reasonably familiar with how to work with it as a library as well as the internals (eg, [RFC 1279](https://github.com/rust-lang/rfcs/pull/1275)). LLVM is a useful tool when you need to generate or run code, and it's frequently interesting to build toys with power tools (like JIT-compiled esoteric languages).

I could find a few ways to put together a talk with a title like this, ranging from building a toy compiler in Rust with the library bindings to how things work under the hood and in rustc- **I'd love to hear opinions** on what others would like to hear.

Some overlap with #21 here, but there's enough going on with LLVM that I could pretty easily disregard the details of working with the C API and just cover LLVM-specific things.

**Comment by bitshifter** [comment]
Yeah, I definitely think it would be of interest and we're always on the lookout for new talks. I don't have any opinions on specifics, both building a toy compiler and how LLVM is used under the hood in Rust would be fine topics.

We have a meetup this Monday (27/02/17), we have a couple of talks already for that and there's not much time left so perhaps the following meetup would be good to aim for. There's also an LLVM meetup in Sydney which you might find interesting if you didn't know about it already, I imagine they are also looking for speakers :)

**Comment by tari** [comment]
Yeah, I didn't expect to be doing this next week, given there are already talks lined up- could do the next one, though (whenever that happens).

I've been to the LLVM meetup; their subjects seem more focused on details and internals and I don't think a more simplistic outside view like I'd give is very useful to them. It's worth further consideration though.

---

I'm leaning toward building a toy, maybe interactively, with side effect of discussing some of how it works internally (since that's a sort of "required reading" to understand how to drive LLVM to do something useful).

**Comment by bitshifter** [comment]
Hi @tari, we're looking at having a meetup in May, probably 15/5 which is Rust's birthday. Are you still interested in giving this talk? The toy compiler idea sounded interesting to me.

**Comment by tari** [comment]
Yeah, I can prepare a talk for the 15th- I agree, a toy compiler of some kind is a good choice.

**Comment by bitshifter** [comment]
Great, I look forward to it!

**Comment by bitshifter** [comment]
I should announce the meetup soon. What will the title of your talk be? Also a short sentence about what it will cover would be good for the announcement too.

**Comment by tari** [comment]
I might be figuratively painting myself into a corner because it hasn't been planned out that far, but close enough!

Let's call it "An Illustrated Guide to LLVM"; an introduction to building simple and not-so-simple compilers with Rust and LLVM.

**Comment by bitshifter** [comment]
Thanks for the talk @tari. Where were your slides living so I can link them from the meetup page?

**Comment by tari** [comment]
The canonical location for the presentation is now https://www.taricorp.net/2017/illustrated-llvm/
