### ISSUE TITLE
Lessons learned from the libz blitz

### ISSUE THREAD

**Issue by KodrAus** [RustSydney/talks#24]
Hi! I'm based in Brisbane and have been involved with the [libz blitz](https://internals.rust-lang.org/t/rust-libz-blitz/5184) this year. I'd be keen to do a reflective talk after the impl period on how it went, what's worked and what we could've done better and some key learnings for engaging an OSS community in general.

Is this something you'd be interested in hearing about? Maybe in Jan/Feb?

**Comment by bitshifter** [comment]
Yep, for sure. Are you going to be down in Sydney at some point? We've had a bit of a hiatus on the meetups but are starting to talk about organising one around Jan/Feb.

**Comment by KodrAus** [comment]
I'm just up in Brisbane so can pop down to Sydney anytime (it's basically quicker to fly to Sydney than it is to take a train through the Brisbane city). Jan or Feb would suit me fine.

Yeh, it's been a while since we've had a meetup in Brisbane too, I've let the ball drop a bit there :(

**Comment by bitshifter** [comment]
Cool! It sounds like our venue is free on Monday the 15th of January, would that work for you?

**Comment by KodrAus** [comment]
Yep, that should work just fine. My email is on my GitHub profile. Please feel free to reach out anytime if you need anything or things change :)

**Comment by bitshifter** [comment]
Can close this one off now, thanks again @KodrAus
