### ISSUE TITLE
Async: considered harmful?

### ISSUE THREAD

**Issue by tari** [RustSydney/talks#25]
In which I explore the current state of I/O intensive workloads in high-performance applications both in Rust and comparing to other languages and attempt to convince the audience that while tools like Tokio are powerful and can be helpful in some applications, they also impose costs on developers that should be carefully considered!

**Comment by bitshifter** [comment]
Sounds good! We haven't decided on a date for the next Meetup, probably in the next couple of months. Sorry it took a while to respond, GitHub notifications don't seem to actually notify me...

**Comment by bitshifter** [comment]
@tari we're thinking about having another meetup mid to late April. Would you be interested in presenting this then?

**Comment by tari** [comment]
Yes, sounds good. (This should motivate me to actually collect my thoughts and write some code!)

**Comment by bitshifter** [comment]
@tari would May 7th be ok for you?

**Comment by tari** [comment]
Yeah, first Monday in May sounds good to me!

**Comment by bitshifter** [comment]
We've got the room booking confirmed, so we're good to go.

**Comment by bitshifter** [comment]
https://www.meetup.com/Rust-Sydney/events/249764935/?rv=co1&_xtd=gatlbWFpbF9jbGlja9oAJDNmMjQ3ZDhmLTFlNjAtNGMwMi05MGM3LWZlNmY5YWJmNDVmZQ
