### ISSUE TITLE
PF Sandbox design decisions and libraries

### ISSUE THREAD

**Issue by rukai** [RustSydney/talks#26]
This is a rough sketch of a talk about my game PF Sandbox. https://pfsandbox.net/
It's mostly at a high level, talking about design decisions and the libraries I used.
Let me know if I should focus more on rust/implementation stuff instead? Or any other feedback?
If I include everything listed here it might be too long, so I'll cut stuff if need be.

# Background (3 min)

Hi everyone, I'm going to be sharing a game I have been working on in my freetime since 2016.
I'm going to talk about some of the design decisions I made and libraries I used to make it happen.

*   What is super smash bros?
*   Why I wanted to make my own smash-like game?
*   Is PF Sandbox a game? Or an engine?

# Demonstrate PF Sandbox (5-10 min)

As I go through this section I will demonstrate in-game what I am referring to.

*   Explain packages.
*   Demonstrate some gameplay
*   Demonstrate character editor.
*   Demonstrate treeflection commands.

# Overview of Technologies used (2 min)

I use nightly rust.
I need it for proc macros though I also like to enable features like nll before they hit stable.
Pinning to a specific nightly release via the rust-toolchain file makes nightly rust usable, especially for CI.

I also rely on lots of libraries:

*   treeflection - pseudo reflection library I wrote, used for the commands I demonstrated earlier
*   winit - cross platform windowing, a game needs a window
*   vulkano - safe vulkan wrapper, a game needs graphics
*   cgmath - computer graphics math library, matrix math is needed
*   lyon - path tesselation library, used to generate vertices for arbitrary stage shapes.
*   rand - random number generator, used for random game mechanics
*   libusb - safe libusb wrapper, used to talk to gamecube controllers
*   gilrs - controller input library, used for all other controllers
*   serde + serde_json - seriazer/deserializer, used for storing character and stage data
*   zip - read/write zip files, used for unzipping packages
*   reqwest - high level http library, used for retrieving packages of characters/stages

# Treeflection (5-10 min)

I found a need for some reflection-like functionality in rust.
But I couldn't find any libraries to do this even though it sounded possible.
In the end I decided to try and build my own.

Talk about how treeflection works to provide user facing reflection-like commands:
*   about proc_macros
*   syntax of commands
*   adding #[derive(Node)] to structs/enums
*   hooking up your own functions as custom commands

# Graphics (5-10 min)

*   Talk about the basic aesthetic I wanted and why I wanted it.
*   Why use glium over a high level graphics library since PF Sandbox is only 2D?
*   Talk about how I started with glium and swapped to vulkano.
*   Talk about the state of these libraries.
*   How I make use of lyon.
*   What about UI?
    +   Currently hacked together by just drawing text
    +   I havn't found a good solution for this. immi?
*   Large delays due to uploading package data to the graphics thread when the editor is used.
    +   mitigation
    +   still unfixed for treeflection

# Controller input (5-10 min)

*   What is gilrs?
*   Why do I use libusb as well as gilrs?
*   Mapping from gilrs xbox input to internal gamecube input.
*   Problems setting up libusb for msvc.

**Comment by bitshifter** [comment]
Hi @rukai . This sounds great! I'll start talking to the other organisers about planning our next meetup since we have a couple of talk proposals now. Any particular dates work or don't work for you?

**Comment by bitshifter** [comment]
We're scheduling the next meetup on Monday 23rd of July, does this date work for you @rukai ?

**Comment by rukai** [comment]
Yes, 23rd of July works for me.

**Comment by bitshifter** [comment]
I missed that you asked for feedback on what to talk about. You probably want to try keep the talk under 45 mins if possible with time for questions afterwards. There's a lot of interesting stuff in there, maybe go a bit deeper on a one or two topics? The reflection and UI areas sound interesting to me in that it sounds like you've spent some time trying to find good solutions in those spaces and perhaps in Rust people haven't settled on a "right way" of solving those problems.

**Comment by whmountains** [comment]
I find the graphics area particularly interesting.  I'm anxious to hear why you chose Glium over Piston or ggez, and why you switched to Vulcan.  A comparison of features as well as an outline of your current graphics pipeline would be very informative.

**Comment by bitshifter** [comment]
Thanks for the talk Lucas, do you have the slides anywhere online that I could share?

**Comment by rukai** [comment]
https://docs.google.com/presentation/d/1l2hzDcp1yxIQrQiRXxpnV4uOeteR2-lLLYtV0AVaeeY/edit?usp=sharing Here you go. I plan on recording the talk and uploading to youtube on my next day off. Will share with everyone when that happens.
