### ISSUE TITLE
Generics, Traits, and Lifetimes

### ISSUE THREAD

**Issue by joshleeb** [RustSydney/talks#27]
## Talk Proposal (10 - 15 minutes)

The talk is based on [Ch10: Generic Types, Traits, and Lifetimes](https://doc.rust-lang.org/book/second-edition/ch10-00-generics.html) of the Rust Book.

I have given an initial (and very casual) version of this talk with [these slides](https://docs.google.com/presentation/d/16dIFfBtF7r-cEi-QYMSziNxixuqKN3t76n6A58ab98Y/edit?usp=sharing) and some follow up exercises listed below. The talk itself needs a fair bit of polish but most of the content and the agenda is there.

### Follow Up Exercises

The follow up exercises from a previous talk.

<details>

#### Part 1

1. Create a generic function called `largest` which takes a generic `Vec` and returns the item with the largest value.
    - Hint: generic type may have to implement `Ord`.
2. Test this for `i32`, `usize`, and `String` types.

#### Part 2

1. Create a generic struct called `Point` which has two attributes of the same type (`x`, and `y`).
2. Create a trait called `MVector` (for matrix-vector), and implement it for `Point`, which has the following method:
    - `dimensions`: returns the number of dimensions.
3. Create a trait called `Magnitude`, and implement it for `Point` which has the following method:
    - `magnitude`: multiplies the square of each attribute.
4. Get the `largest` function to work with `Point`, using `magnitude` to determine the size of the `Point`.

#### Part 3

1. Create another generic struct called `Point3` which has three attributes of the same type (`x`, `y`, and `z`).
2. Implement `MVector` for `Point3`.
3. Implement `Magnitude` for `Point3`.

#### Extension

1. Write a function that takes a list of items that implement `MVector`, and `Magnitude` and displays dot product as well as the number of dimensions
    - Maybe something like this `[2: 100]`, where `2` is the number of dimensions and `100` is the dot product.

[rustbook-ch10]: https://doc.rust-lang.org/book/second-edition/ch10-00-generics.html
[presentation]: https://docs.google.com/presentation/d/16dIFfBtF7r-cEi-QYMSziNxixuqKN3t76n6A58ab98Y
</details>

## Motivation

- This chapter is arguable one of the more important chapters of the Rust Book, since it touches on traits and lifetimes, and it is also one of the harder ones to comprehend.
- I prepared the initial version of this talk for our internal Rust-Club at work.
- At the May meetup there was a call for more beginner focused talks, and I recall someone posting on the meetup group asking for a talk about Ch10 specifically.

**Comment by bitshifter** [comment]
Hi @joshleeb . Sounds good! I'll start talking to the other organisers about planning our next meetup since we have a couple of talk proposals now. Any particular dates work or don't work for you?

**Comment by joshleeb** [comment]
Late August/Early September is no good for me but apart from that I'm pretty flexible.

**Comment by bitshifter** [comment]
We're scheduling the next meetup on Monday 23rd of July, does that work for you?

**Comment by joshleeb** [comment]
Yep that's good for me :+1:

**Comment by joshleeb** [comment]
[A link to the slides for tonight's meetup](https://docs.google.com/presentation/d/17D7QvHJmFXDjBfqau7ak6UOdFmY5O7ZAGEZ3X_inEQE/edit?usp=sharing)
