### ISSUE TITLE
Writing docker-based integration tests with Rust

### ISSUE THREAD

**Issue by thomaseizinger** [RustSydney/talks#28]
At work, we have a lot of integration tests that interact with docker containers. In order to do this cleanly, each test needs its own docker container because allows for parallel tests and overall cleaner test design design.

Because of that, I wrote a small library that makes it very easy to spin up docker containers from within Rust and use them for the lifetime of the test.

I'd like to talk about this library and its design decisions, how it works and how some of Rust's features allow for some neat solutions.

**Structure**:

- Background (why would you even want to do this) ~ 5 minutes
- Show code, explain how it works ~ 10 minutes
- Long-term design decisions regarding the lib ~ 5 minutes

What do you think?

**Comment by bitshifter** [comment]
Sounds good. I'll get in touch when we start planning the next meetup (might be a few months away still).

**Comment by thomaseizinger** [comment]
Thanks!
Looking forward to the talk :)

**Comment by bitshifter** [comment]
Hi Thomas, sorry it's taken an age to get back to you. We're tentatively planning a meetup on the 17th of December. Would you be available then?

**Comment by thomaseizinger** [comment]
Unfortunately not. I am in Europe over Christmas and flying out before the 17th. Happy to do it at the next meetup though :)

**Comment by bitshifter** [comment]
Ah never mind, I will get in touch for the next meetup :)

**Comment by bitshifter** [comment]
Hi @thomaseizinger , would you be available to give this talk on Wednesday the 13th of March?

**Comment by thomaseizinger** [comment]
Yep, should be good! :)

**Comment by bitshifter** [comment]
Great!

**Comment by bitshifter** [comment]
Hey Thomas, I'm just putting together the Meetup announcement. Our other speaker provided a bio so I copied a bit of a bio from your site website and used the description you gave above for the talk summary, it reads:

> Thomas is based in Sydney where he works for the TenX Research Lab CoBloX where we develop the COMIT protocol.
>
> At CoBloX, there are a lot of integration tests that interact with docker containers. In order to do this cleanly, each test needs its own docker container because this allows for parallel tests and overall cleaner test design.
> 
> Thomas wrote a small library that makes it very easy to spin up docker containers from within Rust and use them for the lifetime of the test.
> 
> He will talk about this library and its design decisions, how it works and how some of Rust's features allow for some neat solutions.

Let me know if you're happy to use that or alternatively if you'd like to provide something else or just leave it out entirely.

**Comment by thomaseizinger** [comment]
Small copy/pasta error in the first sentence: `where he works on the COMIT
protocol`.

The rest sounds good!
Looking forward to talk about it :)
