### ISSUE TITLE
Talk about Evcxr - Rust REPL and Jupyter kernel

### ISSUE THREAD

**Issue by davidlattimore** [RustSydney/talks#30]
I was thinking I should really give a talk about [Evcxr](https://github.com/google/evcxr), which I released a few weeks ago. I haven't prepared said talk yet, but will aim to do so soon assuming there is interest in such a talk.

**Comment by bitshifter** [comment]
I saw you posting about Evcxr on reddit, super keen for a talk on this. Not sure when we'll have our next meetup, I'll poke Steve.

**Comment by davidlattimore** [comment]
Thanks. If hosting is a problem, I could see if we could host a meetup at the Google office

**Comment by bitshifter** [comment]
Thanks, I will get back to you on hosting.

**Comment by bitshifter** [comment]
Hey David, we've had a bit of discussion about hosting with Canva and Atlassian being options, however Canva don't have a slot until January and Steve is busy until December so we might not be able to get in to Atlassian until next year anyway. Ideally we were hoping to do something late November or early December, so if you are able to host at Google around that time that might be a better option.

**Comment by davidlattimore** [comment]
OK. I'll see if I get hosting here sorted. Will get back to you

**Comment by bitshifter** [comment]
Hi David, we're able to hold a meetup at Atlassian on the 17th of December. Would that work for you?

**Comment by davidlattimore** [comment]
Yes, that would work for me. Sorry I've been slow getting back to you about hosting one at Google. I managed to determine that it would be fine for me to book a room for the meetup, but was having trouble getting approval to purchase food and drinks. Hopefully the ground-work I set in motion this time might make it easier if I need to organize a meetup here in future.

**Comment by bitshifter** [comment]
Great! No worries around hosting, I imagine it's not that straight forward. Atlassian seem to have a pretty streamlined system.

**Comment by bitshifter** [comment]
How long do you think you'll aim for presentation wise? Up to an hour should be fine.

**Comment by davidlattimore** [comment]
I'd aim for 30-45 minutes I think. Do we have another speaker able to make it on that date?

**Comment by bitshifter** [comment]
The other speaker I had in mind isn't available on that date but we'll sort something out.

**Comment by bitshifter** [comment]
https://www.meetup.com/Rust-Sydney/events/256668602/?rv=co1&_xtd=gatlbWFpbF9jbGlja9oAJGE3YTRkN2VmLTFmYjUtNDE5Zi1hMDRjLWQ3ZTE5MmEzOGZhMw

**Comment by bitshifter** [comment]
Let me know if you want to add/change anything on the talk description

**Comment by davidlattimore** [comment]
Looks good. Thanks
