### ISSUE TITLE
Lightning talk: What's new in Rust 2018

### ISSUE THREAD

**Issue by auscompgeek** [RustSydney/talks#31]
Our next meetup happens to coincide somewhat well with the release of Rust 1.31 and the 2018 edition.

I would like to give a brief overview of what's new in Rust 2018. I'll try to keep it to about 10 minutes.

**Comment by bitshifter** [comment]
I like the idea of covering 2018, I'll talk to the others and see what they think about adding another short talk.

**Comment by bitshifter** [comment]
The other organisers agreed, we'll add you to the line up :)

**Comment by bitshifter** [comment]
@auscompgeek before I update the announcement can you confirm you are good to do this talk, thanks!

**Comment by auscompgeek** [comment]
Yup, I'll be there :+1:

See you on Monday!
