### ISSUE TITLE
Lightning talk proposal: My experience making a graphics thing.

### ISSUE THREAD

**Issue by Ben-PH** [RustSydney/talks#33]
Hi, I'm relatively inexperienced with Rust, but would like to offer to do a quick talk/discussion of my first thing I made.

[See my repo here](https://github.com/Ben-PH/shader_brot/)

I would like to go through my story. My aim would be

- To bring attention to the graphics library I used (`ggez`)
- Compare with similar project that got my attention, and why I chose to take a different path
- Understand how to help the community improve in this area by hearing my trials and triumphs
- Show the first thing that I made that I'm proud of.

I hope 10mins would be sufficient, but I'm happy to run it as a longer format talk if that would work well.

**Comment by bitshifter** [comment]
Sounds good Ben, I'll get back to you about what date we're thinking of.

**Comment by bitshifter** [comment]
Hi @Ben-PH would Monday the 17th of June work for you?

**Comment by bitshifter** [comment]
Actually we're going to push this back to the 24th of June so there's a bit more time, does that work for you?

**Comment by Ben-PH** [comment]
24th is fine, going by the assumption it's an evening event.

**Comment by bitshifter** [comment]
Yep, it's will be between 6pm and 9pm at Atlassian's offices near Wynyard.

**Comment by bitshifter** [comment]
Hi Ben, would you like to provide a brief summary of your talk and bio? It's not at all mandatory, just something I did last time that I think was useful for attendees. E.g. from the last meetup https://www.meetup.com/Rust-Sydney/events/258785543/, could be a lot briefer than that and totally fine if you'd rather not. The new meetup description is here https://www.meetup.com/Rust-Sydney/events/262194894.

**Comment by Ben-PH** [comment]
bio. Student at UNSW, with an interest leaning more towards systems.

For the talk, I just want to quickly go over how I learn't a few things
about Rust, graphics programming, etc.


   - First step: find a crate to make an image on the screen with per pixel
   control
   - Second step was to make it interactive.
   - Once I saw that was working, saw that it was extremely slow.
   - Came to the conclusion that I needed to make a custom shader.
   - wrote the custom shader.

I'll mention points such as

   - Issue with hidpi
   - Minimal resources outside of crate documentation.
   - The very helpful community
   - Working my way through a brand new and unfamiliar domain.

Once I've put some more thought into it, I'll let you know.

**Comment by bitshifter** [comment]
Thanks for giving a talk Ben, feel free to post links to your github and slides on the event page for anyone who is interested https://www.meetup.com/Rust-Sydney/events/262194894/
