### ISSUE TITLE
Lightning Talk: Introducing Rust in a large company

### ISSUE THREAD

**Issue by t-botz** [RustSydney/talks#34]
Hey, 
I could do a talk about my experience introducing Rust in a large company, both on the technical side and the human side of it.

Length: ~20min

**Comment by bitshifter** [comment]
sounds interesting! I will get back to you with a date

**Comment by bitshifter** [comment]
Hi @thibaultdelor would Monday the 17th of June work for you?

**Comment by t-botz** [comment]
Works for me!

**Comment by bitshifter** [comment]
Actually we're going to push this back to the 24th of June so there's a bit more time, does that still work for you?

**Comment by t-botz** [comment]
No worries, still ok for me

**Comment by bitshifter** [comment]
Hi @thibaultdelor , would you like to provide a brief summary of your talk and a bio. It's not at all mandatory, just something I did last time that I think was useful for attendees. E.g. from last meetup https://www.meetup.com/Rust-Sydney/events/258785543/, could be a lot briefer than that and totally fine if you'd rather not. The new meetup description is here https://www.meetup.com/Rust-Sydney/events/262194894.

**Comment by bitshifter** [comment]
Thanks for the talk!

**Comment by rukai** [comment]
Hi @thibaultdelor.
I remember this talk, it was really good!
Do you still happen to have slides available?
