### ISSUE TITLE
Talk Proposal: Lighthouse Ethereum 2.0 Client

### ISSUE THREAD

**Issue by paulhauner** [RustSydney/talks#35]
Hi,
  Thanks for organizing these meetups, they're a great initiative. I missed the last on unfortunately but was at the previous.

I am part of a Sydney-based team that is building an open-source Ethereum 2.0 client in Rust. Ethereum 2.0 replaces proof-of-work with proof-of-stake (much less energy usage) and provides a parallel execution environment.

I don't necessarily want to talk about Etheruem 2.0 (or even "blockchain" for that matter), rather the application we're building: [sigp/lighthouse](https://github.com/sigp/lighthouse). I could give an overview of some of the components we're building in the interest of stimulating conversation. Here's some of the more interesting components:

- [rust-libp2p](https://github.com/libp2p/rust-libp2p): a modular, general purpose p2p stack. Also implemented in Go and JS (with Nim, Java + more coming), libp2p aims to be a simple, drop-in solution for "oh it would be useful if this application could talk via a P2P network". We've been adding protocols and extending it to suit our requirements.
- [signature-schemes](https://github.com/sigp/signature-schemes): Our implementation of BLS cryptography based upon the Apache Milagro epileptic curve library. BLS signatures support "aggregation" where you can aggregate many signatures into a single 96-byte signature and then verify large numbers of them all very quickly (compared to ECDSA).
- [cached_tree_hash](http://lighthouse-docs.sigmaprime.io/cached_tree_hash/index.html): Our in-house library that can perform cached merkle tree updates. E.g., if you have a list of `n` elements it requires `n - 1` hashes to build the tree. Naively, if you only modify a single element of that list you need to do `n - 1` hashes again. With our library you only need to perform `log2(n)` hashes.

We have a functioning testnet client that can sync over a WAN and display metrics via Prometheus/Grafana. We're aiming towards a multi-client testnet (i.e., sync with other implementations of Eth2) in October and starting a formal security review process in the coming months.

Anyway, there's a lot here. If you're interested in hearing a talk about a Lighthouse, perhaps people could indicate what's the most interesting? I will be overseas from the 3rd-17th of June, but if the meetup falls within these days I suspect a colleague can do it.

**Comment by bitshifter** [comment]
Hi Paul, I think we might have enough speakers now for the next meetup, we've had a few people come forward already. I will let you know for sure soon. We are always in need of speakers at future meetups though.

**Comment by paulhauner** [comment]
Copy that, thanks @bitshifter.

**Comment by bitshifter** [comment]
Hi @paulhauner, we're planning a meetup on Tuesday the 29th of October. Would you still be interested in giving a talk at that time? We have a few talk proposals at the moment so I'm trying to find out who is still interested and available initially. Ninja edit: also what kind of duration were you thinking talk wise?

**Comment by paulhauner** [comment]
Hey, thanks for reaching out. We're still interested and the 29th works for us :)

For duration, we could probably do anything from 20mins to an hour :)

**Comment by bitshifter** [comment]
Hi @paulhauner . Lets lock in that talk. Let me know what you want to aim for length wise. Anything from 20 mins to 40 mins excluding question time is good. I'm trying to decide if there's time for a 3rd speaker, no worries if there's not.

Also let me know the title and summary of your talk for the meetup invite when you are able. Feel free to include a bio about yourself if you like, that's totally optional though.

**Comment by bitshifter** [comment]
Event is up https://www.meetup.com/Rust-Sydney/events/265708002/

**Comment by paulhauner** [comment]
Apologies for the delay, I've been overseas and lagging on my Github notifications.

How's a 30 minute talk sound? Happy to adjust to suit the schedule :)

**Comment by bitshifter** [comment]
No worries Paul, 30 mins is good.

**Comment by bitshifter** [comment]
Thanks for the talk Paul! Let me know if you have slides I can link somewhere.

**Comment by paulhauner** [comment]
Thank you @bitshifter!

Slides below :)

https://docs.google.com/presentation/d/1f99_rOgSc54AKUMjO3HWpdOXRkP_fEsp-pIqNlIyVy0/edit?usp=sharing
