### ISSUE TITLE
How to roll your own crypto in rust

### ISSUE THREAD

**Issue by LLFourn** [RustSydney/talks#37]
> Don't roll your own crypto

But if you do, it's important to know which crates are out there to help you down your path of irresponsibility. This talk will be about using and implementing crypto crates in rust. 

- Why would you roll your own crypto and how rust is making this terrible practice more accessible.
- What is the state of crypto in rust? How [const generics](https://github.com/rust-lang/rust/issues/44580) will help.
- A few examples of where rolling your own crypto might be better than whatever you were about to do anyway.
- What are the best crypto crates in rust that help you avoid the pitfalls of rolling your own.

Crates I will touch on are mostly in:
- https://github.com/RustCrypto
- https://github.com/dalek-cryptography

**Comment by bitshifter** [comment]
Awesome, we'll get in touch when we're planning the next meetup. Probably not for a few months.

**Comment by bitshifter** [comment]
Hi @LLFourn  , we're planning a meetup on Tuesday the 29th of October. Would you still be interested in giving a talk at that time? If so, what kind of duration were you thinking for your talk? We have a few talk proposals at the moment so I'm trying to find out who is still interested and available initially.

**Comment by LLFourn** [comment]
Hi. Yep I would love to do this one on the 29th if there's space. I should also be available in December/January if this one is full but probably not Feb/March.

**Comment by bitshifter** [comment]
How long do you think you'd like your talk to be @LLFourn? Anything between 20 and 40 mins + time for questions should be good. I'm trying to work out of we can do 2 or 3 talks. Will include you either way.

**Comment by LLFourn** [comment]
Oops sorry. Yeah I think just 25 mins for the presentation will be enough. Thanks.

**Comment by bitshifter** [comment]
Cool, let me know the title and summary of your talk for the meetup invite when you are able. Feel free to include a bio about yourself if you like, totally optional though.

**Comment by bitshifter** [comment]
Event is up https://www.meetup.com/Rust-Sydney/events/265708002/

**Comment by LLFourn** [comment]
Thanks. I love the description! Looking forward to it.

**Comment by bitshifter** [comment]
Thanks for the talk Lloyd! Let me know if your slides are available somewhere.

**Comment by LLFourn** [comment]
slides with half baked code are here: https://github.com/LLFourn/rust-sydney-pwless. Thanks it was fun :)
