### ISSUE TITLE
When Rust meets the next generation graph database

### ISSUE THREAD

**Issue by zhengyi-yang** [RustSydney/talks#38]
My colleagues and I from the University of New South Wales have been working on building the next generation of distributed graph database using Rust in the last two years. Currently, we have built a prototype system which are completely written in Rust. Thanks to Rust and the algorithm we have, our system can achieve a very high performance that significantly outperforms the-state-of-the-art up to several orders of magnitude.

The system will be released in the future. I can share my experience of developing large-scale big data system using Rust and the reason why we choose Rust and why Rust is so fast.

I haven't prepare for the talk, but I think it might be an interesting topic to share to other people :)

**Comment by bitshifter** [comment]
Hi @zhengyi-yang , we're planning a meetup on Tuesday the 29th of October. Would you still be interested in giving a talk at that time? If so, what kind of duration were you thinking for your talk? We have a few talk proposals at the moment so I'm trying to find out who is still interested and available initially.

**Comment by zhengyi-yang** [comment]
Hi @bitshifter, I'll be able to give the talk. The duration can be about 20 min

**Comment by bitshifter** [comment]
Hi @zhengyi-yang we have enough speaker for the meetup on the 29th now, we had three people volunteer a while ago and they're all available that night. So we'll try get you in our next meetup, whenever that is.

**Comment by zhengyi-yang** [comment]
@bitshifter No worries. That's totally ok. See you in the next meetup

**Comment by bitshifter** [comment]
Hi @zhengyi-yang would you be available to give this talk on Monday 24th of Feb? We have two talks lined up already but I think we could still fit you in.

**Comment by zhengyi-yang** [comment]
Hi @bitshifter, that's no problem! How long should my talk be?

**Comment by bitshifter** [comment]
Great! I would say no longer than 30 minutes would be fine.

**Comment by zhengyi-yang** [comment]
Sure :) I think my talk will be about 20 minutes
