### ISSUE TITLE
Are talks recorded?

### ISSUE THREAD

**Issue by lunacookies** [RustSydney/talks#39]
I took a look on YouTube, but couldn't find a canonical location for past talks. Are they not recorded, or have I just not looked in the right places?

Thanks.

**Comment by bitshifter** [comment]
They haven't usually been recorded unfortunately so you're not missing anything. It's down to the venue and I think the rooms we've been in haven't been set up for recording.

**Comment by lunacookies** [comment]
Ah, thanks for the info.
