### ISSUE TITLE
linear lambda calculus and the search for an embeddable interpreter

### ISSUE THREAD

**Issue by srijs** [RustSydney/talks#4]
When looking for small languages to embed within Rust programs, existing solutions are often heavyweight, or don't fit well within Rust's ownership model, which results in complex APIs.

A linear lambda is a function which must use its argument exactly once. Sounds familiar? This is very similar to how memory ownership works in Rust.

Linear lambda calculus (LLC, for short) is the calculus built around those linear lambda functions. An interpreter for LLC is a surprisingly well-suited problem to solve in Rust, and the practical benefits of the ownership model are carried into the guest language almost effortlessly.

I can give a small talk (15-20 minutes) going into some detail about the interpreter I am writing, and describe some of the problems I encountered, and the solutions to them.

**Comment by michaelsproul** [comment]
This sounds rad!

**Comment by caspark** [comment]
Would you mind dropping a link to your slides here @srijs ?

**Comment by srijs** [comment]
See #6
