### ISSUE TITLE
Distro packaging of the Rust toolchain

### ISSUE THREAD

**Issue by anguslees** [RustSydney/talks#7]
What's involved, a state-of-the-union of Debian Rust packaging, and the outstanding issues.
Mostly Debian focussed, but also a discussion of other distros (as much as I'm able).

(I don't think I'm allowed to set the `proposal` label on this?)

**Comment by caspark** [comment]
Sounds interesting. Does Tuesday December 1st (starting at 6pm as usual) work for you?

(it's kind of annoying that Github doesn't allow everyone to set labels - clearly I should've set up a JIRA instance for this instead :P)

**Comment by anguslees** [comment]
Unusually, I'm out at the northern beaches all day that day - I can't guarantee that I won't be late :/

Some other month might work better, or otherwise I can do 1st Dec and we just see what happens...

**Comment by caspark** [comment]
Would you be likely to be able to make 7pm? We likely won't start talks until 18:30, and #8 could go before you for about half an hour (I'd save you some pizza ;).

Or, does Tuesday 15th of December work better for you? (I don't know if that's good for #8 yet, but IIRC that's the only other day in December that works venue-wise)

**Comment by anguslees** [comment]
Tues 15th works better for me, but that sounds like I'm imposing my schedule on everyone else.  I think I can arrive by 7pm (or not much after) on Tues 1st.

**Comment by caspark** [comment]
Well, to some extent speakers are allowed to impose schedules - as long as they cooperate with each other and the venue ;)

I'll see what #9 says about Dec 1st.

**Comment by caspark** [comment]
Okay, I'll stick with Dec 1st and list this talk as a _Probably_. If timing doesn't work out on the day then that's alright; we'll have future meetups too (but I'd appreciate a heads-up if you decide not to come on the day).

**Comment by caspark** [comment]
@anguslees would you please make your slides available here? Either as a PR to this repo or a link to where they can be obtained.

**Comment by anguslees** [comment]
Slides are here: http://anguslees.github.io/talks/2015-12-01-rust-packaging/reveal.pdf

**Comment by caspark** [comment]
Thanks!
