### ISSUE TITLE
Your first contributions in Rust

### ISSUE THREAD

**Issue by absoludity** [RustSydney/talks#9]
I started learning rust recently and as part of my initial learning, landed [some](https://github.com/servo/euclid/commit/046c1f811c1e1d0aad560224bce3b87c2ce03298) [small](https://github.com/servo/euclid/commit/84150a904899957cb32e1c54fa31ad9100937507)  commits for euclid (a servo dependency). If there was interest, I'd be happy to spend 10mins chatting informally at a meetup about the experience as a newcomer, something like:
- motivation for learning rust,
- resources that were most helpful for active learning (and what's missing, IMO)
- finding ways to contribute code as a newcomer (basically, find smaller dependencies like Euclid, improving tests as a way to better understand the code)

**Comment by caspark** [comment]
Sure, it's always good to get those first impressions, and chances are it'll be helpful to others attending.

Does Tuesday December 1st, 6pm work for you? (6pm being pizza & drinks, talks are after that)

**Comment by absoludity** [comment]
If Tuesdays are the standard night for Rust meetups, that works -  I can do Tues, but a Weds, Thurs or Fri would suit better (wouldn't have to cancel a local code-club, but it's not a big deal). 6pm on any night Tues-Friday that week works for me.

**Comment by absoludity** [comment]
Just read the comment on #7 - so sounds like Tuesdays are the day. That's fine - either 1st or 15th works for me.

**Comment by caspark** [comment]
Ah, sorry about that. Atlassian hosts a lot of meetups and as a result for the rest of this year there's only 2 Tuesdays available, so it has to be a Tuesday in the short term.

Let's make it the 1st then. (edit: sooner being better than later, given people go places for holidays and we're overdue for a meetup)

**Comment by caspark** [comment]
@absoludity would you please make your slides available here? Either as a PR to this repo or a link to where they can be obtained.

**Comment by absoludity** [comment]
@caspark Sure - there's not much info (I didn't get a chance to add notes), but for the record: [Your first contributions to rust](https://docs.google.com/presentation/d/1Rk9fqY-Zi1-oc7B2ui1UNnlS177l4GxsvXq5ccIxHzA/edit?usp=sharing)

Thanks for hosting!
